finbourne/lusid-sdk-csharp

lusid-sdk-csharp/LusidSdk.Tests/LusidApiTests.cs, lusid-sdk-csharp/LusidSdk/ILUSIDAPI.cs, lusid-sdk-csharp/LusidSdk/LUSIDAPI.cs, lusid-sdk-csharp/LusidSdk/LUSIDAPIExtensions.cs, lusid-sdk-csharp/LusidSdk/Models/ClearEntityCachesDto.cs, lusid-sdk-csharp/LusidSdk/Models/CorporateActionEventDto.cs, lusid-sdk-csharp/LusidSdk/Models/CorporateActionTransitionDto.cs, lusid-sdk-csharp/LusidSdk/Models/ErrorResponse.cs, lusid-sdk-csharp/LusidSdk/Models/HoldingDto.cs, lusid-sdk-csharp/LusidSdk/Models/ReconciliationBreakDto.cs, lusid-sdk-csharp/LusidSdk/Models/SecurityAnalyticDataDto.cs, lusid-sdk-csharp/LusidSdk/Models/TradeDto.cs, lusid-sdk-csharp/LusidSdk/Models/TxnMetaDataDto.cs, lusid-sdk-csharp/LusidSdk/Models/TxnMovementMetaDataDto.cs, lusid-sdk-csharp/LusidSdk/Models/TxnTypeAliasDto.cs, lusid-sdk-csharp/LusidSdk/Models/UpsertCorporateActionRequest.cs, lusid.json
- Fix issue in test (TradeDto.TradeDate is now nullable)
See also: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/690
- Check in updated API spec
- Check in updated models
=> DEV-1277: update C# SDK tests following Swashbuckle upgrade

lusid-sdk-csharp/LusidSdk.Tests/LusidApiTests.cs
Concrete types are now returned from methods
Test for lookup of schema from entity result
=> DEV-1388 Updates to tests after API changes

lusid-sdk-csharp/LusidSdk.Tests/LusidApiTests.cs
DEV-1327 Fix security mappings
=> DEV-1327 Fix security mappings

sdk/Lusid.Sdk.Tests/tutorials/Ibor/Portfolios.cs
=> DEV-4032: Fix sdk tests

sdk/Lusid.Sdk.Tests/tutorials/MarketData/InstrumentMaster.cs
=> TR-282: Fix API changes

sdk/Lusid.Sdk.Tests/Utilities/DateTimeOrCutLabelTests.cs, sdk/Lusid.Sdk/Utilities/DateTimeOrCutLabel.cs
=> DEV-4597 Add Equals operator to DateTimeOrCutLabel

sdk/Lusid.Sdk.Tests/tutorials/Ibor/Holdings.cs
=> DEV-1799 Added validation of ListHoldingsAdjustments

sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs, sdk/Lusid.Sdk/Utilities/LusidApiFactoryBuilder.cs, sdk/Lusid.Sdk/Utilities/TokenProviderConfiguration.cs
=> DEV-6405 Refactor creation of the LusidApiFactory to be threadsafe

sdk/Dockerfile, sdk/Lusid.Sdk.Tests/Lusid.Sdk.Tests.csproj
=> DEV-6967 Upgrade tests to .Net Core 3.1

sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs, sdk/Lusid.Sdk/Lusid.Sdk.csproj, sdk/Lusid.Sdk/Utilities/ApiClient.cs, sdk/Lusid.Sdk/Utilities/ApiConfiguration.cs, sdk/Lusid.Sdk/Utilities/ApiConfigurationBuilder.cs, sdk/Lusid.Sdk/Utilities/ApiExceptionExtensions.cs, sdk/Lusid.Sdk/Utilities/LusidApiFactory.cs
Update project references and fix compilation errors
=> DEV-7032 Updates for OpenAPI generator 4.3.0

sdk/Lusid.Sdk.Tests/tutorials/Ibor/Reconciliation.cs, sdk/Lusid.Sdk.Tests/tutorials/MarketData/InstrumentMaster.cs
=> DEV-7749 OpenApi Test changes

sdk/Lusid.Sdk.Tests/tutorials/Ibor/ReferencePorfolios.cs
=> add tests for ref port

sdk/Lusid.Sdk.Tests/tutorials/Ibor/Properties.cs, sdk/Lusid.Sdk/Utilities/PropertyExtensions.cs
Fixes a comparer used in tests introduced by https://github.com/finbourne/lusid-sdk-csharp/pull/72.
=> DEV-8462 Part 2: Support multi-value properties (patch test)

sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs
=> DEV-9680: Fixed errorResonseDetails message

.github/workflows/run-sdk-tests.yaml
Amending the slack message on PR failure.
=> Feature/se 463.update slack message with branch

sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs
Account for hex encoding of value
=> SE-542 Account for hex encoding of value

sdk/Lusid.Sdk.Tests/Lusid.Sdk.Tests.csproj, sdk/Lusid.Sdk.Tests/tutorials/Ibor/Bitemporal.cs, sdk/Lusid.Sdk.Tests/tutorials/Ibor/Holdings.cs, sdk/Lusid.Sdk.Tests/tutorials/Ibor/Portfolios.cs, sdk/Lusid.Sdk.Tests/tutorials/Ibor/Properties.cs, sdk/Lusid.Sdk.Tests/tutorials/Ibor/Reconciliation.cs, sdk/Lusid.Sdk.Tests/tutorials/Ibor/ReferencePorfolios.cs, sdk/Lusid.Sdk.Tests/tutorials/Ibor/Transactions.cs, sdk/Lusid.Sdk.Tests/tutorials/MarketData/InstrumentMaster.cs, sdk/Lusid.Sdk.sln, sdk/LusidFeatureReporter/LusidFeatureReporter.cs, sdk/LusidFeatureReporter/LusidFeatureReporter.csproj
=> SE-304 Add feature reporter

sdk/Lusid.Sdk.Tests/tutorials/Ibor/ReferencePorfolios.cs
Rename portfolio codes to be unique to each test, delete portfolio after tests are complete.
=> SE-1045 Rename to unique portfolio codes, delete portfolio after test

sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs
Update test for update LUSID error message
=> SE-1121 Fix test for updated error message 

sdk/Dockerfile, sdk/Examples/Examples.csproj, sdk/Examples/HelloWorld.cs, sdk/Lusid.Sdk.Tests/Lusid.Sdk.Tests.csproj, sdk/Lusid.Sdk.Tests/tutorials/HelloWorld/HelloWorldTest.cs, sdk/Lusid.Sdk.sln
Hello World Example to use in the Quick Start Guide.
=> SE-1150: Create HelloWorld.cs

README.md
=> SE-1286: Fix typo

sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs, sdk/Lusid.Sdk/Client/ApiClient.cs, sdk/Lusid.Sdk/Lusid.Sdk.csproj, sdk/Lusid.Sdk/Utilities/ApiExceptionExtensions.cs, sdk/Lusid.Sdk/Utilities/ApiResponseExtensions.cs, sdk/Lusid.Sdk/Utilities/LusidApiFactory.cs
=> Manual SDK changes

sdk/Lusid.Sdk/Utilities/ApiResponseExtensions.cs
=> one more SDK change

sdk/Lusid.Sdk/Utilities/ApiResponseExtensions.cs
Reverts finbourne/lusid-sdk-csharp#100
=> Revert "one more SDK change"

sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs, sdk/Lusid.Sdk/Lusid.Sdk.csproj, sdk/Lusid.Sdk/Utilities/ApiExceptionExtensions.cs, sdk/Lusid.Sdk/Utilities/ApiResponseExtensions.cs, sdk/Lusid.Sdk/Utilities/LusidApiFactory.cs
This reverts commit 06cd79a0ee6b8c14d2e3a4f8e418dbb15a9fd498.
=> Revert "Manual SDK changes for Open API upgrade (#99)"

sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs, sdk/Lusid.Sdk/Lusid.Sdk.csproj, sdk/Lusid.Sdk/Utilities/ApiExceptionExtensions.cs, sdk/Lusid.Sdk/Utilities/ApiResponseExtensions.cs, sdk/Lusid.Sdk/Utilities/LusidApiFactory.cs
=> Api upgrade take2

sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs, sdk/Lusid.Sdk/Lusid.Sdk.csproj, sdk/Lusid.Sdk/Utilities/ApiExceptionExtensions.cs, sdk/Lusid.Sdk/Utilities/ApiResponseExtensions.cs, sdk/Lusid.Sdk/Utilities/LusidApiFactory.cs
Reverts finbourne/lusid-sdk-csharp#103
=> Revert "Api upgrade take2"

sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs, sdk/Lusid.Sdk/Lusid.Sdk.csproj, sdk/Lusid.Sdk/Utilities/ApiExceptionExtensions.cs, sdk/Lusid.Sdk/Utilities/ApiResponseExtensions.cs, sdk/Lusid.Sdk/Utilities/LusidApiFactory.cs
This reverts commit 0064e2cb0e30bd1bc22349f69d4d2b8fa1333fd8.
=> Manual SDK changes for Open API upgrade

sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs, sdk/Lusid.Sdk/Lusid.Sdk.csproj, sdk/Lusid.Sdk/Utilities/ApiExceptionExtensions.cs, sdk/Lusid.Sdk/Utilities/ApiResponseExtensions.cs, sdk/Lusid.Sdk/Utilities/LusidApiFactory.cs
Reverts finbourne/lusid-sdk-csharp#106
=> Revert "Manual SDK changes for Open API upgrade"

sdk/Lusid.Sdk/Lusid.Sdk.csproj
Update RestSharp to fix security vulnerability
=> CTECH-719 update RestSharp 106.15.0

sdk/Lusid.Sdk.Tests/tutorials/Ibor/Bitemporal.cs, sdk/Lusid.Sdk.Tests/tutorials/Ibor/Holdings.cs, sdk/Lusid.Sdk.Tests/tutorials/Ibor/Portfolios.cs, sdk/Lusid.Sdk.Tests/tutorials/Ibor/Properties.cs, sdk/Lusid.Sdk.Tests/tutorials/Ibor/Reconciliation.cs, sdk/Lusid.Sdk.Tests/tutorials/Ibor/ReferencePorfolios.cs, sdk/Lusid.Sdk.Tests/tutorials/Ibor/Transactions.cs, sdk/Lusid.Sdk.Tests/tutorials/MarketData/InstrumentMaster.cs
- Migrated legacy labels of features in the csharp SDK to labels that reflect logical groupings e.g portfolios, instruments etc.
=> migrated csharp sdk feature list to updated features

sdk/Lusid.Sdk.Tests/tutorials/Ibor/Portfolios.cs, sdk/Lusid.Sdk.Tests/tutorials/Ibor/Transactions.cs, sdk/Lusid.Sdk.Tests/tutorials/MarketData/InstrumentMaster.cs
- Completed the migration of feature labels
- Ran the feature reporter locally and successfully
=> Ctech 404.feature

sdk/LusidFeatureReporter/LusidFeatureReporter.csproj
Update feature reporter version
=> Update feature reporter

sdk/Lusid.Sdk.Tests/tutorials/Ibor/Portfolios.cs, sdk/Lusid.Sdk.Tests/tutorials/Ibor/Transactions.cs, sdk/Lusid.Sdk.Tests/tutorials/MarketData/InstrumentMaster.cs
=> updated features

sdk/Lusid.Sdk/Lusid.Sdk.csproj
Updated Newtonsoft from 12.0.3 to 13.0.1
=> CTECH-1497 Bump Newtonsoft version in the SDK project

sdk/Lusid.Sdk/Utilities/ApiResponseExtensions.cs
make requestId header check case insensitive
=> make requestId header check case insensitive

.readthedocs.yaml
=> Fix for enforced Readthedocs build config change

docs/index.rst
=> Another fix for Readthedocs build config change

.readthedocs.yaml, docs/requirements.txt
=> Tweak to try and get inheritance diagrams working again

.readthedocs.yaml
=> Try again with graphviz after readthedocs build failure
